### ISSUE TITLE
[INFO] raw output: 199

### ISSUE THREAD

**Issue by MadhuPristine** [bhimrazy/receipt-ocr#1]
Hi, To understand functionality of this library, i have followed exact steps mentioned in the readme. But all my attempts "python main.py -i d:\work\Learning\OCR\poc2\images\receipt1.jpeg" ends with below message 
[INFO] raw output:
==================
199

Any idea why above output

**Comment by bhimrazy** [comment]
Hi @MadhuPristine,

Thank you for creating an issue.

The problem you encountered is likely due to the quality of the image, which wasn't properly detected by the algorithm using the default parameters. Some adjustments to the parameters or the edge detector might resolve the issue (though it may not be a robust solution).

Here is an explanation of the process:
> You can extract sections by saving images at intermediate steps.
![image](https://github.com/bhimrazy/receipt-ocr/assets/46085301/305df68d-50d8-41d4-81d0-9324966fb6c9)

In the example you tried, the algorithm was unable to detect the actual receipt region.

I have updated the README with another example that you can try. Feel free to ask if you have any more questions or need further clarification.

Thank you!
